import {IChargeback} from '@utils/interfaces';

export class Chargeback implements IChargeback {
  id = null
  merchant_number = null
  post_date = null
  item_type = null
  card_number = null
  acquirer_reference = null
  rc_code = null
  rc_description = null
  currency = null
  amount = null
  cnn = null
  original_post_date = null
  original_transaction_date = null
  original_type = null
  original_transaction_currency = null
  original_transaction_amount = null
  merchant_settlement_currency = null
  merchant_settlement_amount = null
  network_settlement_currency = null
  network_settlement_amount = null
  original_slip = null
  item_slip_number = null
  auth_code = null
  batch_number = null
  merchant_dba_name = null
  merchant_transaction_reference = null
  capture_method = null
  member_message_text = null
  document_indicator = null
  retrieval_request_id = null
  chargeback_reference_id = null
  due_date = null
  central_processing_date = null
  work_by_date = null
  chargeback_amount = null
  chargeback_currency = null
  partial_amount = null
  chargeback_account_amount = null
  chargeback_account_currency = null
  e_wallet_type = null
  vme_add_auth_method = null
  vme_add_auth_reason_code = null
  ppol_program_data = null
  processed_transaction_id = null
  merchant_id = null
  merchant_name = null;
  created_at = null
  updated_at = null
  case_id = null
  item_type_code = null
  original_chargeback_slip = null
  client_number = null
  merchant_funding_currency = null
  merchant_funding_amount = null
  authorization_record_sequence = null
  previous_transfer_to_merchant = null
  unique_tran_id = null
  dispute_condition_code = null

  constructor(c?: IChargeback) {
    if (c) {
      this.id = c.id ? c.id : null;
      this.merchant_number = c.merchant_number ? c.merchant_number : null;
      this.post_date = c.post_date ? c.post_date : null;
      this.item_type = c.item_type ? c.item_type : null;
      this.card_number = c.card_number ? c.card_number : null;
      this.acquirer_reference = c.acquirer_reference ? c.acquirer_reference : null;
      this.rc_code = c.rc_code ? c.rc_code : null;
      this.rc_description = c.rc_description ? c.rc_description : null;
      this.currency = c.currency ? c.currency : null;
      this.amount = c.amount ? c.amount : null;
      this.cnn = c.cnn ? c.cnn : null;
      this.original_post_date = c.original_post_date ? c.original_post_date : null;
      this.original_transaction_date = c.original_transaction_date ? c.original_transaction_date : null;
      this.original_type = c.original_type ? c.original_type : null;
      this.original_transaction_currency = c.original_transaction_currency ? c.original_transaction_currency : null;
      this.original_transaction_amount = c.original_transaction_amount ? c.original_transaction_amount : null;
      this.merchant_settlement_currency = c.merchant_settlement_currency ? c.merchant_settlement_currency : null;
      this.merchant_settlement_amount = c.merchant_settlement_amount ? c.merchant_settlement_amount : null;
      this.network_settlement_currency = c.network_settlement_currency ? c.network_settlement_currency : null;
      this.network_settlement_amount = c.network_settlement_amount ? c.network_settlement_amount : null;
      this.original_slip = c.original_slip ? c.original_slip : null;
      this.item_slip_number = c.item_slip_number ? c.item_slip_number : null;
      this.auth_code = c.auth_code ? c.auth_code : null;
      this.batch_number = c.batch_number ? c.batch_number : null;
      this.merchant_dba_name = c.merchant_dba_name ? c.merchant_dba_name : null;
      this.merchant_transaction_reference = c.merchant_transaction_reference ? c.merchant_transaction_reference : null;
      this.capture_method = c.capture_method ? c.capture_method : null;
      this.member_message_text = c.member_message_text ? c.member_message_text : null;
      this.document_indicator = c.document_indicator ? c.document_indicator : null;
      this.retrieval_request_id = c.retrieval_request_id ? c.retrieval_request_id : null;
      this.chargeback_reference_id = c.chargeback_reference_id ? c.chargeback_reference_id : null;
      this.due_date = c.due_date ? c.due_date : null;
      this.central_processing_date = c.central_processing_date ? c.central_processing_date : null;
      this.work_by_date = c.work_by_date ? c.work_by_date : null;
      this.chargeback_amount = c.chargeback_amount ? c.chargeback_amount : null;
      this.chargeback_currency = c.chargeback_currency ? c.chargeback_currency : null;
      this.partial_amount = c.partial_amount ? c.partial_amount : null;
      this.chargeback_account_amount = c.chargeback_account_amount ? c.chargeback_account_amount : null;
      this.chargeback_account_currency = c.chargeback_account_currency ? c.chargeback_account_currency : null;
      this.e_wallet_type = c.e_wallet_type ? c.e_wallet_type : null;
      this.vme_add_auth_method = c.vme_add_auth_method ? c.vme_add_auth_method : null;
      this.vme_add_auth_reason_code = c.vme_add_auth_reason_code ? c.vme_add_auth_reason_code : null;
      this.ppol_program_data = c.ppol_program_data ? c.ppol_program_data : null;
      this.processed_transaction_id = c.processed_transaction_id ? c.processed_transaction_id : null;
      this.merchant_id = c.merchant_id ? c.merchant_id : null;
      this.merchant_name = c.merchant_name ? c.merchant_name : null;
      this.created_at = c.created_at ? c.created_at : null;
      this.updated_at = c.updated_at ? c.updated_at : null;
      this.case_id = c.case_id ? c.case_id : null;
      this.item_type_code = c.item_type_code ? c.item_type_code : null;
      this.original_chargeback_slip = c.original_chargeback_slip ? c.original_chargeback_slip : null;
      this.client_number = c.client_number ? c.client_number : null;
      this.merchant_funding_currency = c.merchant_funding_currency ? c.merchant_funding_currency : null;
      this.merchant_funding_amount = c.merchant_funding_amount ? c.merchant_funding_amount : null;
      this.authorization_record_sequence = c.authorization_record_sequence ? c.authorization_record_sequence : null;
      this.previous_transfer_to_merchant = c.previous_transfer_to_merchant ? c.previous_transfer_to_merchant : null;
      this.unique_tran_id = c.unique_tran_id ? c.unique_tran_id : null;
      this.dispute_condition_code = c.dispute_condition_code ? c.dispute_condition_code : null;
    }
  }
}
